name: Publish Docker image

on:
  push:
    branches:
      - 'feature/deployment'
        
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
      
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Quali.Torque.Cli/Dockerfile
        push: true
